const productItems = [
    {
        id: '1',
        name: 'CÁ THU KHO TỘ',
        price: '100,000 VND',
        sale: '50%',
        img: '/assets/img/products/product1.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
        rate: 0,
    },
    {
        id: '2',
        name: 'CÁ KHO TỘ CHAY',
        price: '100,000 VND',
        sale: '0%',
        img: '/assets/img/products/product2.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
        rate: 5,
    },
    {
        id: '3',
        name: 'GIÒ NẤM 1KG',
        price: '90,250 VND',
        sale: '5%',
        img: '/assets/img/products/product3.jpg',
        tag: 'Hàng Chay Cấp Đông',
        category: 'Hàng Chay Cấp Đông',
        rate: 5,
    },
    {
        id: '4',
        name: 'CHẢ LÁ LỐT',
        price: '45,000 VND',
        sale: '10%',
        img: '/assets/img/products/product4.jpg',
        tag: 'Hàng Chay Cấp Đông',
        category: 'Hàng Chay Cấp Đông',
        rate: 4,
    },
    {
        id: '5',
        name: 'CÁ KÈO',
        price: '45,000 VND',
        sale: '10%',
        img: '/assets/img/products/product5.jpg',
        tag: 'Hàng Chay Cấp Đông',
        category: 'Hàng Chay Cấp Đông',
        rate: 0,
    },
    {
        id: '6',
        name: 'DỒI CHAY',
        price: '44,550 VND',
        sale: '1%',
        img: '/assets/img/products/product6.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
        rate: 5,
    },
    {
        id: '7',
        name: 'KHOAI MÔN',
        price: '55,440 VND',
        sale: '1%',
        img: '/assets/img/products/product7.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
        rate: 5,
    },
    {
        id: '8',
        name: 'THỊT NƯỚNG',
        price: '45,000 VND',
        sale: '10%',
        img: '/assets/img/products/product8.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
        rate: 3,
    },
    {
        id: '9',
        name: 'BÒ XÀO',
        price: '45,000 VND',
        sale: '10%',
        img: '/assets/img/products/product9.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
        rate: 2,
    },
    {
        id: '10',
        name: 'BÁNH GỐI',
        price: '100,000 VND',
        sale: '50%',
        img: '/assets/img/products/product10.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
        rate: 1,
    },
    {
        id: '11',
        name: 'DỒI CHAY',
        price: '100,000 VND',
        sale: '50%',
        img: '/assets/img/products/product11.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
        rate: 0,
    },
    {
        id: '12',
        name: 'ĐÙI GÀ CHAY',
        price: '100,000 VND',
        sale: '50%',
        img: '/assets/img/products/product12.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
        rate: 5,
    },
    {
        id: '13',
        name: 'SALAD RAU',
        price: '45,000 VND',
        sale: '50%',
        img: '/assets/img/products/product16.jpg',
        tag: 'Món Nộm',
        category: 'Món Nộm',
        rate: 5,
    },
    {
        id: '14',
        name: 'SUSHI',
        price: '45,000 VND',
        sale: '50%',
        img: '/assets/img/products/product19.jpg',
        tag: 'Món Cơm',
        category: 'Món Cơm',
        rate: 5,
    },
];

export default productItems;
