const productItems = [
    {
        id: '1',
        name: 'CÁ THU KHO TỘ',
        price: '100,000 VND',
        sale: '50%',
        img: '/assets/img/products/product1.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
    },
    {
        id: '2',
        name: 'CÁ KHO TỘ CHAY',
        price: '100,000 VND',
        sale: '',
        img: '/assets/img/products/product2.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
    },
    {
        id: '3',
        name: 'GIÒ NẤM 1KG',
        price: '90,250 VND',
        sale: '5%',
        img: '/assets/img/products/product3.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
    },
    {
        id: '4',
        name: 'CHẢ LÁ LỐT',
        price: '45,000 VND',
        sale: '10%',
        img: '/assets/img/products/product4.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
    },
    {
        id: '5',
        name: 'CÁ KÈO',
        price: '45,000 VND',
        sale: '10%',
        img: '/assets/img/products/product5.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
    },
    {
        id: '6',
        name: 'DỒI CHAY',
        price: '44,550 VND',
        sale: '1%',
        img: '/assets/img/products/product6.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
    },
    {
        id: '7',
        name: 'KHOAI MÔN LỆ PHỐ HÀ NỘI',
        price: '55,440 VND',
        sale: '1%',
        img: '/assets/img/products/product7.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
    },
    {
        id: '8',
        name: 'THỊT NƯỚNG',
        price: '45,000 VND',
        sale: '10%',
        img: '/assets/img/products/product8.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
    },
    {
        id: '9',
        name: 'BÒ XÀO',
        price: '45,000 VND',
        sale: '10%',
        img: '/assets/img/products/product9.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
    },
    {
        id: '10',
        name: 'BÁNH GỐI',
        price: '100,000 VND',
        sale: '50%',
        img: '/assets/img/products/product10.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
    },
    {
        id: '11',
        name: 'DỒI CHAY',
        price: '100,000 VND',
        sale: '50%',
        img: '/assets/img/products/product11.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
    },
    {
        id: '12',
        name: 'ĐÙI GÀ CHAY',
        price: '100,000 VND',
        sale: '50%',
        img: '/assets/img/products/product12.jpg',
        tag: 'Món Chay Mặn',
        category: 'Món Chay Mặn',
    },
];

export default productItems;
